/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PhysioResource } from "./api/physio";
export { PhysioResource } from "./api/physio";
export namespace Components {
    interface WacPhysioApp {
        "apiBase": string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "api-base"?: string;
        "basePath": string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "base-path"?: string;
    }
    interface WacPhysioDashboard {
        "apiBase": string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "api-base"?: string;
        "refreshToken": number;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "refresh-token"?: number;
        "selectedResource": PhysioResource;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "selected-resource"?: PhysioResource;
    }
    interface WacPhysioEditor {
        "apiBase": string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "api-base"?: string;
        "recordId": string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "record-id"?: string;
        "resource": PhysioResource;
    }
}
export interface WacPhysioDashboardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWacPhysioDashboardElement;
}
export interface WacPhysioEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWacPhysioEditorElement;
}
declare global {
    interface HTMLWacPhysioAppElement extends Components.WacPhysioApp, HTMLStencilElement {
    }
    var HTMLWacPhysioAppElement: {
        prototype: HTMLWacPhysioAppElement;
        new (): HTMLWacPhysioAppElement;
    };
    interface HTMLWacPhysioDashboardElementEventMap {
        "resource-selected": PhysioResource;
        "record-opened": { resource: PhysioResource; id: string };
    }
    interface HTMLWacPhysioDashboardElement extends Components.WacPhysioDashboard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWacPhysioDashboardElementEventMap>(type: K, listener: (this: HTMLWacPhysioDashboardElement, ev: WacPhysioDashboardCustomEvent<HTMLWacPhysioDashboardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWacPhysioDashboardElementEventMap>(type: K, listener: (this: HTMLWacPhysioDashboardElement, ev: WacPhysioDashboardCustomEvent<HTMLWacPhysioDashboardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWacPhysioDashboardElement: {
        prototype: HTMLWacPhysioDashboardElement;
        new (): HTMLWacPhysioDashboardElement;
    };
    interface HTMLWacPhysioEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLWacPhysioEditorElement extends Components.WacPhysioEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWacPhysioEditorElementEventMap>(type: K, listener: (this: HTMLWacPhysioEditorElement, ev: WacPhysioEditorCustomEvent<HTMLWacPhysioEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWacPhysioEditorElementEventMap>(type: K, listener: (this: HTMLWacPhysioEditorElement, ev: WacPhysioEditorCustomEvent<HTMLWacPhysioEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWacPhysioEditorElement: {
        prototype: HTMLWacPhysioEditorElement;
        new (): HTMLWacPhysioEditorElement;
    };
    interface HTMLElementTagNameMap {
        "wac-physio-app": HTMLWacPhysioAppElement;
        "wac-physio-dashboard": HTMLWacPhysioDashboardElement;
        "wac-physio-editor": HTMLWacPhysioEditorElement;
    }
}
declare namespace LocalJSX {
    interface WacPhysioApp {
        "apiBase"?: string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "api-base"?: string;
        "basePath"?: string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "base-path"?: string;
    }
    interface WacPhysioDashboard {
        "apiBase"?: string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "api-base"?: string;
        "onRecord-opened"?: (event: WacPhysioDashboardCustomEvent<{ resource: PhysioResource; id: string }>) => void;
        "onResource-selected"?: (event: WacPhysioDashboardCustomEvent<PhysioResource>) => void;
        "refreshToken"?: number;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "refresh-token"?: number;
        "selectedResource"?: PhysioResource;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "selected-resource"?: PhysioResource;
    }
    interface WacPhysioEditor {
        "apiBase"?: string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "api-base"?: string;
        "onEditor-closed"?: (event: WacPhysioEditorCustomEvent<string>) => void;
        "recordId"?: string;
        /**
         * @deprecated use camelCase instead. Support for dash-casing will be removed in Stencil v5.
         */
        "record-id"?: string;
        "resource"?: PhysioResource;
    }
    interface IntrinsicElements {
        "wac-physio-app": WacPhysioApp;
        "wac-physio-dashboard": WacPhysioDashboard;
        "wac-physio-editor": WacPhysioEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wac-physio-app": LocalJSX.WacPhysioApp & JSXBase.HTMLAttributes<HTMLWacPhysioAppElement>;
            "wac-physio-dashboard": LocalJSX.WacPhysioDashboard & JSXBase.HTMLAttributes<HTMLWacPhysioDashboardElement>;
            "wac-physio-editor": LocalJSX.WacPhysioEditor & JSXBase.HTMLAttributes<HTMLWacPhysioEditorElement>;
        }
    }
}
